# Generated by Django 5.1.4 on 2025-02-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('usertype', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Studentreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admno', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('department', models.CharField(max_length=40)),
                ('semester', models.IntegerField()),
                ('contactno', models.CharField(max_length=10)),
            ],
        ),
    ]
