# Generated by Django 5.1.4 on 2025-03-12 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('usertype', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=40)),
                ('sem', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=40)),
                ('sem', models.CharField(max_length=40)),
                ('course1', models.CharField(max_length=40)),
                ('course2', models.CharField(max_length=40)),
                ('course3', models.CharField(max_length=40)),
                ('course4', models.CharField(max_length=40)),
                ('ecourse1', models.CharField(max_length=40)),
                ('ecourse2', models.CharField(max_length=40)),
                ('ecourse3', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Studentreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='uploads/')),
                ('admno', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField(max_length=20)),
                ('department', models.CharField(max_length=40)),
                ('semester', models.IntegerField()),
                ('contactno', models.CharField(max_length=10)),
                ('login_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_as_loginid', to='EduVance.login')),
            ],
        ),
        migrations.CreateModel(
            name='ElectiveCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electives', to='EduVance.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='EduVance.subject')),
            ],
        ),
        migrations.CreateModel(
            name='teacherreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tphoto', models.FileField(upload_to='uploads/')),
                ('tname', models.CharField(max_length=50)),
                ('tgender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=20)),
                ('tdepartment', models.CharField(max_length=40)),
                ('tcontactno', models.CharField(max_length=10)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.login')),
            ],
        ),
        migrations.CreateModel(
            name='Omr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omr', models.FileField(upload_to='uploads/')),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.login')),
                ('tc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.teacherreg')),
            ],
        ),
        migrations.CreateModel(
            name='InternalMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.studentreg')),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.teacherreg')),
            ],
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay', models.FileField(upload_to='uploads/')),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.login')),
                ('tea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.teacherreg')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField(auto_now_add=True)),
                ('present', models.IntegerField(default=0)),
                ('absent', models.IntegerField(default=0)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.studentreg')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.teacherreg')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.FileField(upload_to='uploads/')),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.studentreg')),
                ('ta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.teacherreg')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.FileField(upload_to='uploads/')),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.login')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.teacherreg')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elective_course', models.CharField(max_length=40)),
                ('semester', models.CharField(max_length=20)),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.studentreg')),
            ],
            options={
                'unique_together': {('stud_id', 'semester')},
            },
        ),
    ]
