# Generated by Django 5.1.4 on 2025-02-02 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreg',
            name='login_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='EduVance.login'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='dob',
            field=models.CharField(max_length=20),
        ),
    ]
