# Generated by Django 5.1.4 on 2025-03-12 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalmarks',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='EduVance.subject'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='internalmarks',
            unique_together={('stud_id', 'subject')},
        ),
    ]
