# Generated by Django 5.1.4 on 2025-03-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0002_internalmarks_subject_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
