# Generated by Django 5.1.4 on 2025-02-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0002_studentreg_login_id_alter_studentreg_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreg',
            name='dob',
            field=models.DateField(max_length=20),
        ),
    ]
