# Generated by Django 5.1.4 on 2025-02-15 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0003_alter_studentreg_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50)),
                ('tgender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=20)),
                ('tdepartment', models.CharField(max_length=40)),
                ('tcontactno', models.CharField(max_length=10)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.login')),
            ],
        ),
    ]
