# Generated by Django 5.0 on 2025-03-12 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0003_delete_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalmarks',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.course'),
        ),
    ]
