# Generated by Django 5.1.4 on 2025-02-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0004_teacherreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay', models.FileField(upload_to='uploads')),
                ('current_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
