# Generated by Django 5.1.4 on 2025-03-14 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0004_alter_internalmarks_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.CharField(max_length=100)),
                ('replay', models.CharField(max_length=100)),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.studentreg')),
            ],
        ),
    ]
