# Generated by Django 5.1.4 on 2025-02-22 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0006_alter_essay_essay'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='login_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='EduVance.login'),
            preserve_default=False,
        ),
    ]
