# Generated by Django 5.1.4 on 2025-03-21 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0006_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='tid',
        ),
    ]
