# Generated by Django 5.1.4 on 2025-04-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0007_remove_exam_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherreg',
            name='tcertificate',
            field=models.FileField(default=0, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
