# Generated by Django 5.1.4 on 2025-03-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0008_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreg',
            name='photo',
            field=models.FileField(default=0, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherreg',
            name='tphoto',
            field=models.FileField(default=0, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
