# Generated by Django 5.1.4 on 2025-04-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0008_teacherreg_tcertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
