# Generated by Django 5.1.4 on 2025-04-03 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0009_login_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherreg',
            name='login_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='t', to='EduVance.login'),
        ),
    ]
