# Generated by Django 5.1.4 on 2025-03-02 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0009_studentreg_photo_teacherreg_tphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='t_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='EduVance.teacherreg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='essay',
            name='tea_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='EduVance.teacherreg'),
            preserve_default=False,
        ),
    ]
