# Generated by Django 5.1.4 on 2025-04-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0010_alter_teacherreg_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherreg',
            name='texp',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherreg',
            name='tqualification',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherreg',
            name='treferenceletter',
            field=models.FileField(default=0, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
