# Generated by Django 5.1.4 on 2025-04-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0011_teacherreg_texp_teacherreg_tqualification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minor1', models.CharField(max_length=60, null=True)),
                ('minor2', models.CharField(max_length=60, null=True)),
                ('aec_a', models.CharField(max_length=60, null=True)),
                ('aec_b', models.CharField(max_length=60, null=True)),
                ('mdc', models.CharField(max_length=60, null=True)),
                ('vac1', models.CharField(max_length=60, null=True)),
                ('vac2', models.CharField(max_length=60, null=True)),
                ('sec', models.CharField(max_length=60, null=True)),
            ],
        ),
    ]
