# Generated by Django 5.1.4 on 2025-03-04 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0011_alter_studentreg_login_id_omr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.FileField(upload_to='uploads/')),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.login')),
                ('ta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.teacherreg')),
            ],
        ),
    ]
