# Generated by Django 5.1.4 on 2025-03-04 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0012_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='login_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.studentreg'),
        ),
    ]
