# Generated by Django 5.1.4 on 2025-04-05 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0012_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='subjectid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='EduVance.subject'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ElectiveCourse2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elective2', to='EduVance.subject')),
            ],
        ),
    ]
