# Generated by Django 5.1.4 on 2025-04-05 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0013_subjects_subjectid_electivecourse2'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minors', models.TextField(blank=True, null=True)),
                ('aec', models.TextField(blank=True, null=True)),
                ('mdc', models.CharField(blank=True, max_length=60, null=True)),
                ('vac', models.TextField(blank=True, null=True)),
                ('sec', models.CharField(blank=True, max_length=60, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='EduVance.subject')),
            ],
        ),
    ]
