# Generated by Django 5.1.4 on 2025-03-05 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0013_alter_assignment_login_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('present', models.CharField(max_length=10)),
                ('absent', models.CharField(max_length=10)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.studentreg')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.teacherreg')),
            ],
        ),
    ]
