# Generated by Django 5.1.4 on 2025-04-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0014_subjectdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectdetail',
            name='elective_courses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
