# Generated by Django 5.1.4 on 2025-03-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0014_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='absent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='present',
            field=models.IntegerField(),
        ),
    ]
