# Generated by Django 5.1.4 on 2025-03-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0015_alter_attendance_absent_alter_attendance_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='absent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='present',
            field=models.IntegerField(default=0),
        ),
    ]
