# Generated by Django 5.1.4 on 2025-03-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0016_alter_attendance_absent_alter_attendance_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='current_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
