# Generated by Django 5.1.4 on 2025-04-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0016_rename_aec_subjectdetail_aeca_subjectdetail_aecb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectdetail',
            old_name='elective_courses',
            new_name='elective1',
        ),
        migrations.RenameField(
            model_name='subjectdetail',
            old_name='minors',
            new_name='elective2',
        ),
        migrations.RenameField(
            model_name='subjectdetail',
            old_name='vac',
            new_name='major1',
        ),
        migrations.AddField(
            model_name='subjectdetail',
            name='major2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectdetail',
            name='major3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectdetail',
            name='minorsone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectdetail',
            name='minortwo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectdetail',
            name='vac1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectdetail',
            name='vac2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
