# Generated by Django 5.1.4 on 2025-04-13 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0017_rename_elective_courses_subjectdetail_elective1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubjectSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minorsone', models.CharField(blank=True, max_length=100, null=True)),
                ('minortwo', models.CharField(blank=True, max_length=100, null=True)),
                ('aeca', models.CharField(blank=True, max_length=100, null=True)),
                ('aecb', models.CharField(blank=True, max_length=100, null=True)),
                ('mdc', models.CharField(blank=True, max_length=100, null=True)),
                ('vac1', models.CharField(blank=True, max_length=100, null=True)),
                ('vac2', models.CharField(blank=True, max_length=100, null=True)),
                ('sec', models.CharField(blank=True, max_length=100, null=True)),
                ('elective1', models.CharField(blank=True, max_length=100, null=True)),
                ('elective2', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.studentreg')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EduVance.subjectdetail')),
            ],
        ),
    ]
