# Generated by Django 5.1.4 on 2025-03-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0018_internals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=40)),
                ('sem', models.CharField(max_length=40)),
                ('course1', models.CharField(max_length=40)),
                ('course2', models.CharField(max_length=40)),
                ('course3', models.CharField(max_length=40)),
                ('course4', models.CharField(max_length=40)),
                ('ecourse1', models.CharField(max_length=40)),
                ('ecourse2', models.CharField(max_length=40)),
                ('ecourse3', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='internals',
            old_name='ta_id',
            new_name='t_id',
        ),
    ]
