# Generated by Django 5.1.4 on 2025-03-07 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0019_subjects_rename_ta_id_internals_t_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='course',
            new_name='dept',
        ),
        migrations.DeleteModel(
            name='Internals',
        ),
    ]
