# Generated by Django 5.1.4 on 2025-03-08 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0020_rename_course_subjects_dept_delete_internals'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elective_course', models.CharField(max_length=40)),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.studentreg')),
            ],
        ),
    ]
