# Generated by Django 5.1.4 on 2025-04-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0021_teacherreg_teacherid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherreg',
            name='teacherid',
            field=models.CharField(editable=False, max_length=40, unique=True),
        ),
    ]
