# Generated by Django 5.1.4 on 2025-04-18 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0022_alter_teacherreg_teacherid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='internalmarks',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='internalmarks',
            name='subjects',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='EduVance.subjectdetail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internalmarks',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.studentsubjectselection'),
        ),
        migrations.AlterUniqueTogether(
            name='internalmarks',
            unique_together={('stud_id', 'subject', 'subjects')},
        ),
    ]
