# Generated by Django 5.1.4 on 2025-04-18 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0023_alter_internalmarks_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subjects',
        ),
    ]
