# Generated by Django 5.1.4 on 2025-05-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0025_alter_internalmarks_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherreg',
            name='is_hod',
            field=models.BooleanField(default=False),
        ),
    ]
