# Generated by Django 5.1.4 on 2025-05-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0026_teacherreg_is_hod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjectadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major1', models.TextField(blank=True, null=True)),
                ('major2', models.TextField(blank=True, null=True)),
                ('major3', models.TextField(blank=True, null=True)),
                ('minorsone', models.TextField(blank=True, null=True)),
                ('minortwo', models.TextField(blank=True, null=True)),
                ('aeca', models.TextField(blank=True, null=True)),
                ('aecb', models.TextField(blank=True, null=True)),
                ('mdc', models.CharField(blank=True, max_length=60, null=True)),
                ('vac1', models.TextField(blank=True, null=True)),
                ('vac2', models.TextField(blank=True, null=True)),
                ('sec', models.CharField(blank=True, max_length=60, null=True)),
                ('elective1', models.TextField(blank=True, null=True)),
                ('elective2', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
