# Generated by Django 5.1.4 on 2025-05-01 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0027_subjectadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectadd',
            name='subject',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='deta', to='EduVance.subject'),
            preserve_default=False,
        ),
    ]
