# Generated by Django 4.2.11 on 2025-05-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0028_subjectadd_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='omr',
            name='question_paper',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
