# Generated by Django 4.2.11 on 2025-05-01 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0029_omr_question_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField()),
                ('details', models.TextField()),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.answer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.login')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.teacherreg')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluatedAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_paper', models.FileField(upload_to='evaluated_papers/')),
                ('total_marks', models.FloatField()),
                ('evaluated_on', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='EduVance.answer')),
            ],
        ),
    ]
