# Generated by Django 5.1.4 on 2025-05-03 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0030_evaluationresult_evaluatedanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectadd',
            name='hod',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='EduVance.teacherreg'),
            preserve_default=False,
        ),
    ]
