# Generated by Django 5.1.4 on 2025-05-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0031_subjectadd_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
