# Generated by Django 5.1.4 on 2025-05-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0032_essay_grade_essay_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='essay',
            name='mark',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
