# Generated by Django 5.1.4 on 2025-05-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0033_alter_essay_grade_alter_essay_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='mark',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
