# Generated by Django 5.1.4 on 2025-05-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0034_assignment_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
