# Generated by Django 5.1.4 on 2025-05-05 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0035_essay_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='login_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.studentreg'),
        ),
    ]
