# Generated by Django 5.1.4 on 2025-05-05 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0036_alter_essay_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='student',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='EduVance.studentreg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='essay',
            name='login_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.login'),
        ),
    ]
